"""Regenerate runs/LEDGER.md from each run's own summary.json.

Regenerated rather than appended: several runs finish concurrently on two GPUs,
and concurrent appends to one markdown file lose rows. Each run owns its
summary.json; the ledger is a view over them.

    python scripts/update_ledger.py

CLAUDE.md §10: update after every session. This becomes the compute appendix.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

HEADER = """# Run ledger

Regenerated by `python scripts/update_ledger.py`. Do not hand-edit rows: each
run's `summary.json` is the source of truth. Free-text notes go under
[Session notes](#session-notes), which the script preserves.

| run_id | config hash | date | status | GPU-hours | device | tasks | notes |
|---|---|---|---|---:|---|---:|---|
"""

NOTES_MARKER = "## Session notes"
DEFAULT_NOTES = """
## Session notes

_Add per-session commentary here; the generator preserves everything below this
heading._
"""


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--runs-root", default=str(ROOT / "runs"))
    ap.add_argument("--out", default=str(ROOT / "runs" / "LEDGER.md"))
    args = ap.parse_args(argv)

    runs_root = Path(args.runs_root)
    out = Path(args.out)

    rows, total_hours = [], 0.0
    for d in sorted(p for p in runs_root.iterdir() if p.is_dir()) if runs_root.exists() else []:
        cfg_path, sum_path = d / "config.json", d / "summary.json"
        if not cfg_path.exists():
            continue
        cfg = json.loads(cfg_path.read_text(encoding="utf-8"))
        if sum_path.exists():
            s = json.loads(sum_path.read_text(encoding="utf-8"))
            status, hours = s.get("status", "?"), float(s.get("gpu_hours", 0.0))
            device, n_tasks = s.get("device", "?"), s.get("n_tasks", "?")
            chash = s.get("config_hash", "?")
        else:
            # Present but unfinished: a killed session, or one still running.
            status, hours, device, chash = "incomplete", 0.0, "?", "?"
            n_tasks = cfg.get("data", {}).get("n_tasks", "?")
        total_hours += hours
        date = datetime.fromtimestamp(
            cfg_path.stat().st_mtime, tz=timezone.utc
        ).strftime("%Y-%m-%d")
        note = str(cfg.get("notes", "")).replace("|", "/")
        rows.append(
            f"| `{cfg['run_id']}` | `{chash}` | {date} | {status} | "
            f"{hours:.2f} | {device} | {n_tasks} | {note} |"
        )

    existing_notes = DEFAULT_NOTES
    if out.exists():
        text = out.read_text(encoding="utf-8")
        if NOTES_MARKER in text:
            existing_notes = "\n" + text[text.index(NOTES_MARKER) :]

    body = HEADER + ("\n".join(rows) if rows else "| _(no runs yet)_ | | | | | | | |")
    body += f"\n\n**Total: {len(rows)} runs, {total_hours:.2f} GPU-hours.**\n"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(body + existing_notes, encoding="utf-8")
    print(f"wrote {out}: {len(rows)} runs, {total_hours:.2f} GPU-hours")
    return 0


if __name__ == "__main__":
    sys.exit(main())
